# Generated by Django 4.0.3 on 2022-04-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='users/avatars/default_user_avatar.png', upload_to='users/avatars/'),
        ),
    ]
